theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: none
theme_advanced_styles: "Code=codeStyle;Quote=quoteStyle"
paste_auto_cleanup_on_paste: true
paste_remove_spans: true
entity_encoding: raw
plugins:
  - bbcode
  - emotions
  - paste
theme_advanced_buttons1:
  - cleanup
  - "|"
  - fontselect
  - fontsizeselect
  - "|"
  - forecolor
  - emotions
  - "|"
  - undo
  - redo
theme_advanced_buttons2:
  - bold
  - italic
  - underline
  - "|"
  - justifyleft
  - justifycenter
  - justifyright
  - "|"
  - bullist
  - numlist
  - outdent
  - indent
  - "|"
  - link
  - unlink
  - image
  - blockquote